services:

  backend:
    container_name: sds_chatbot
    build:
      context: .
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - qdrant  
    volumes:
      - ./static:/app/static
    

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"  
      - "6334:6334"  
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage: